package com.hospital.activity;
import java.util.ArrayList;
final public class SpecialityData {
	private ArrayList<String> speciality;
	public ArrayList<String> specialityOutput() {
		speciality=new ArrayList<String>();
		speciality.add("Cardiovascular");
		speciality.add("General Practice");
		speciality.add("Psychiatry");
		speciality.add("Cardiology");
		speciality.add("Neurology");
		speciality.add("Gynaecology");
		speciality.add("Gerontology");
		speciality.add("Pulmonology");
		speciality.add("Pathology");
		speciality.add("Orthopedics");
		speciality.add("Pediatrics");
		speciality.add("Dermatology");
		speciality.add("Endocrinology");
		speciality.add("Gastroenterology");
		speciality.add("Oncology");
		speciality.add("Urology");
		speciality.add("ENT Specialist");
		speciality.add("Otolaryngology");
		speciality.add("Ophthalmology");
		speciality.add("Toxicology");
		speciality.add("Allergology");
		speciality.add("Hematology");
		speciality.add("Hepatology");
		speciality.add("Palliative medicine");
		speciality.add("Podiatry");
		speciality.add("Rheumatology");
		speciality.add("Radiology");
		speciality.add("Oral and maxillofacial surgery");
		speciality.add("Transplantation medicine");
		speciality.add("Nuclear medicine");
		speciality.add("Sleep medicine");
		speciality.add("Serology");
		speciality.add("Sexual health");
		speciality.add("Surgery (Other)");
		speciality.add("Immunology");
		speciality.add("Infectious diseases");
		speciality.add("Intensive care medicine");
		speciality.add("General Practice");
		speciality.add("Psychiatry");
		speciality.add("Bariatrics Surgery");
		speciality.add("Cardiac surgery");
		speciality.add("Eye surgery");
		speciality.add("General surgery");
		speciality.add("Neurosurgery");
		speciality.add("Ophthalmology Surgery");
		speciality.add("Plastic surgery");
		speciality.add("Surgical oncology");
		speciality.add("Thoracic surgery");
		speciality.add("Vascular surgery");
		speciality.add("Urology");
		speciality.add("Traumatology");
		speciality.add("Proctology");
		speciality.add("PCP");
		speciality.add("Obstetrics");
		speciality.add("General Medicine");
		speciality.add("Family Medicine");
		speciality.add("Opthalmology");
		speciality.add("Osteopathy");
		speciality.add("Internal Medicine");
		return speciality;
	}
}